### ISSUE TITLE
Width wrap_content doesn't work when setting manual primaryDialMaxSizeDp

### ISSUE THREAD

**Issue by tytydraco** [Swordfish90/RadialGamePad#7]
The wrap_content seems to work fine on the FrameLayout containers with the default dial configuration, however, after manually setting primaryDialMaxSizeDp to a smaller number, the container does not resize to the new dial size. 
![Screenshot_20201028-151018](https://user-images.githubusercontent.com/19982371/97502316-23855f80-1930-11eb-97aa-c30f4a75548d.jpg)

**Comment by Swordfish90** [comment]
Thank you for reporting it. I just fixed the issue in #9
